INSERT INTO MEMBER (USER_ID,ROLE,PWD,CREATE_DATE,MODIFY_DATE) VALUES('user@abc.def','USER','$2a$10$.haloPAOqfTMgNJBU4SPUeyNAYIJoto3vTbVtkSsbaRL8mz2mUd2K',NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2024','01',100,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2024','02',200,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2024','03',300,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2024','04',400,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2024','05',500,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2024','06',600,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2024','07',700,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2024','08',800,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2024','09',900,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2024','10',100,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2024','11',200,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2024','12',300,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2025','01',100,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2025','02',200,NOW(),NOW());
INSERT INTO SALE_DATA (sale_Year,sale_Month,Sale_Amount,CREATE_DATE,MODIFY_DATE) VALUES('2025','03',300,NOW(),NOW());



